dog_aid_project/dog_aid/urls.py
from django.urls import path
from dog_aid import views

app_name = 'dog_aid'

urlpatterns = [
    path('', views.first, name='first'),
    path('index/', views.index, name='index'),
    path('quiz/', views.quiz, name='quiz'),
    path('training/', views.training, name='training'),
    path('vet_register/', views.registerVet, name='vet_register'),
    path('register_dog/', views.register_dog, name='register_dog'),
    path('register_event/', views.registerDogEvent, name='register_event'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('dog_profile/<name>/', views.DogProfileView.as_view(), name='dog_profile'),
    path('vet_profile/<name>/', views.VetProfileView.as_view(), name='vet_profile'),
    path('profiles/', views.ListProfilesView.as_view(), name='list_profiles'),
    path('dog_profile_list/', views.ListDogProfiles.as_view(), name='dog_profile_list'),
    path('vet_list/', views.ListVetProfiles.as_view(), name='vet_list'),
    path('register/', views.register, name='register'),
    path('suggest/', views.illness_suggest, name='illness_suggest'),
    path('emergency_suggest/', views.emergency_suggest, name='emergency_suggest'),
    path('illness_profile/<name>/', views.IllnessView.as_view(), name='illness_profile'),
    path('symptom_profile/<name>/', views.SymptomView.as_view(), name='symptom_profile'),
    path('illness_all/', views.ListIllnessView.as_view(), name='illness_all'),
    path('emergency/', views.ListSymptomsIllnessView.as_view(), name='emergency')
]

dog_aid_project/dog_aid_project/urls.py
from django.contrib import admin
from django.urls import path, include
from dog_aid import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.urls import reverse

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('dog_aid:register_profile')

urlpatterns = [
    path('', views.index, name='index'),
    path('dog_aid/', include('dog_aid.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dog_aid_project/dog_aid/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    def __str__(self):
        return self.user.username

class DogBreed(models.Model):
    name = models.CharField(max_length=128)
    type = models.CharField(max_length=128)
    def __str__(self):
        return self.name

class Dog(models.Model):
    dog_id = models.IntegerField(default=0)
    picture = models.ImageField(upload_to='dog_images', blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, max_length=128, null=True)
    name = models.CharField(max_length=128, blank=True)
    DOB = models.DateField(max_length=128, null=True)
    breed = models.ForeignKey(DogBreed, on_delete=models.CASCADE, max_length=128, blank=True)
    def __str__(self):
        return self.name

class DogEventType(models.Model):
    dog_event_id = models.IntegerField(default=0)
    name = models.CharField(max_length=128)
    def __str__(self):
        return self.name

class DogEvent(models.Model):
    name = models.CharField(max_length=128, blank=True)
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE, null=True)
    event_type = models.ForeignKey(DogEventType, on_delete=models.CASCADE)
    date = models.DateField(max_length=128, null=True)
    notes = models.TextField(max_length=1000, blank=True)
    def __str__(self):
        return self.name

class VetType(models.Model):
    vet_type_id = models.IntegerField(default=0)
    name = models.CharField(max_length=128, blank=True)
    def __str__(self):
        return self.name

class Vet(models.Model):
    name = models.CharField(max_length=128, blank=True)
    phone_number = models.CharField(max_length=500)
    address = models.CharField(max_length=500, blank=True)
    type = models.ForeignKey(VetType, on_delete=models.CASCADE, null=True)
    dog_owner = models.ForeignKey(User, on_delete=models.CASCADE, max_length=128, null=True)
    def __str__(self):
        return self.name

class Symptom(models.Model):
    symptom_id = models.IntegerField(default=0)
    name = models.CharField(max_length=128)
    description = models.TextField(max_length=1000, blank=True)
    picture = models.ImageField(upload_to='symptom_images', blank=True)
    def __str__(self):
        return self.name

class Illness(models.Model):
    illness_id = models.IntegerField(default=0)
    name = models.CharField(max_length=128, blank=True)
    description = models.TextField(max_length=1000, blank=True)
    picture = models.ImageField(upload_to='illness_images', blank=True)
    related_symptom = models.ManyToManyField(Symptom)
    treatment = models.TextField(max_length=1000, blank=True)
    call_vet = models.TextField(max_length=300, blank=True)
    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
       return self.title

dog_aid_project/dog_aid/forms.py
from django import forms
from django.contrib.auth.models import User
from dog_aid.models import UserProfile, Dog, Vet, DogEvent

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)
        labels = {
            "picture": "Profile Picture"
        }

class DogForm(forms.ModelForm):
    class Meta:
        model = Dog
        fields = ('owner', 'name', 'DOB', 'breed', 'picture')
        labels = {
            "name": "Name (first name only, one word)",
            "DOB": "Date of Birth",
            "picture": "Profile Picture"
        }

class VetForm(forms.ModelForm):
    class Meta:
        model = Vet
        fields = ('name', 'phone_number', 'address', 'type', 'dog_owner')
        labels = {
            "type": "Priority of Vet",
        }

class DogEventForm(forms.ModelForm):
    class Meta:
        model = DogEvent
        fields = ('name', 'dog', 'event_type', 'date', 'notes')
        labels = {
            'name': 'Name of Event',
            'event_type': 'Type of Event',
            'date': 'Date of Event'
        }

dog_aid_project/dog_aid/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from dog_aid.forms import UserForm, DogForm, VetForm, UserProfileForm, DogEventForm
from django.contrib.auth.models import User
from dog_aid.models import UserProfile, Dog, Vet, Symptom, Illness, DogEvent
from django.utils.decorators import method_decorator
from django.views import View

def index(request):
    return render(request, 'dog_aid/index.html')

def quiz(request):
    return render(request, 'dog_aid/quiz.html')

def training(request):
    return render(request, 'dog_aid/training.html')

def first(request):
    return render(request, 'dog_aid/first.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'dog_aid/registration_form.html', context={'user_form': user_form,
                                                                      'profile_form': profile_form,
                                                                      'registered': registered})

@login_required
def register_dog(request):
    dog_form = DogForm()

    if request.method == 'POST':
        dog_form = DogForm(request.POST, request.FILES)

        if dog_form.is_valid():
            dog_profile = dog_form.save(commit=False)
            dog_profile.save()

            return redirect(reverse('dog_aid:index'))

        else:
            print(dog_form.errors)

    context_dict = {'dog_form': dog_form}
    return render(request, 'dog_aid/profile_registration.html', context_dict)

@login_required
def registerVet(request):
    form = VetForm()

    if request.method == 'POST':
        form = VetForm(request.POST, request.FILES)

        if form.is_valid():
            vet_profile = form.save(commit=False)
            vet_profile.user = request.user
            vet_profile.save()

            return redirect(reverse('dog_aid:index'))

        else:
            print(form.errors)

    context_dict = {'form': form}
    return render(request, 'dog_aid/vet_register.html', context_dict)

class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserForm()
        return (user, user_profile, form)

    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('dog_aid:index'))

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'dog_aid/profile.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('dog_aid:index'))

        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('dog_aid:profile', user.username)
        else:
            print(form.errors)

        context_dict = {'user_profile': user_profile,
                        'selected_user': user, 'form': form}

        return render(request, 'dog_aid/profile.html', context_dict)

class DogProfileView(View):
    def get_dog_details(self, name):
        try:
            dog = Dog.objects.get(name=name)
        except dog.DoesNotExist:
            return None

        dog_profile = Dog.objects.get_or_create(name=name)[0]
        dog_form = DogForm()
        event_profile = DogEvent.objects.filter(dog=dog).order_by('-date')
        return (dog, dog_profile, dog_form, event_profile)

    @method_decorator(login_required)
    def get(self, request, name):
        try:
            (dog, dog_profile, dog_form, event_profile) = self.get_dog_details(name)
            event_profile = DogEvent.objects.filter(dog=dog).order_by('-date')
        except TypeError:
            return redirect(reverse('dog_aid:index'))

        context_dict = {'dog_profile': dog_profile,
                        'selected_dog': dog,
                        'dog_form': dog_form,
                        'event': event_profile}

        return render(request, 'dog_aid/dog_profile.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (dog, dog_profile, dog_form, event_profile) = self.get_dog_details(name)
        except TypeError:
            return redirect(reverse('dog_aid:index'))

        dog_form = DogForm(request.POST, request.FILES, instance=dog)
        if dog_form.is_valid():
            dog_form.save(commit=True)
            return redirect('dog_aid:dog_profile', dog.name)
        else:
            print(dog_form.errors)

        context_dict = {'dog_profile': dog_profile,
                        'selected_dog': dog,
                        'dog_form': dog_form,
                        'event': event_profile}

        return render(request, 'dog_aid/dog_profile.html', context_dict)

@login_required
def registerDogEvent(request):
    event_form = DogEventForm()

    if request.method == 'POST':
        event_form = DogEventForm(request.POST, request.FILES)

        if event_form.is_valid():
            event_profile = event_form.save(commit=False)
            event_profile.save()

            return redirect(reverse('dog_aid:index'))

        else:
            print(event_form.errors)

    context_dict = {'event_form': event_form}
    return render(request, 'dog_aid/register_dog_event.html', context_dict)

class VetProfileView(View):
    def get_vet_details(self, name):
        try:
            vet = Vet.objects.get(name=name)
        except vet.DoesNotExist:
            return None

        vet_profile = Vet.objects.get_or_create(name=name)[0]
        vet_form = VetForm()
        return (vet, vet_profile, vet_form)

    @method_decorator(login_required)
    def get(self, request, name):
        try:
            (vet, vet_profile, vet_form) = self.get_vet_details(name)
        except TypeError:
            return redirect(reverse('dog_aid:index'))

        context_dict = {'vet_profile': vet_profile,
                        'selected_vet': vet,
                        'vet_form': vet_form}

        return render(request, 'dog_aid/vet_profile.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, name):
        try:
            (vet, vet_profile, vet_form) = self.get_vet_details(name)
        except TypeError:
            return redirect(reverse('dog_aid:index'))

        vet_form = VetForm(request.POST, request.FILES, instance=vet)
        if vet_form.is_valid():
            vet_form.save(commit=True)
            return redirect('dog_aid:vet_profile', vet.name)
        else:
            print(vet_form.errors)

        context_dict = {'vet_profile': vet_profile,
                        'selected_vet': vet, 'vet_form': vet_form}

        return render(request, 'dog_aid/vet_profile.html', context_dict)

class SymptomView(View):
    def get_symptom_details(self, name):
        try:
            symptom = Symptom.objects.get(name=name)
        except symptom.DoesNotExist:
            return None
        return symptom

    def get(self, request, name):
        try:
            symptom = self.get_symptom_details(name)
        except TypeError:
            return redirect(reverse('dog_aid:index'))

        illness_list = symptom.illness_set.all()

        context_dict = {'selected_symptom': symptom,
                        'illness_list': illness_list}

        return render(request, 'dog_aid/symptom_profile.html', context_dict)

class IllnessView(View):
    def get_illness_details(self, name):
        try:
            illness = Illness.objects.get(name=name)
        except illness.DoesNotExist:
            return None
        return illness

    def get(self, request, name):
        try:
            illness = self.get_illness_details(name)
        except TypeError:
            return redirect(reverse('dog_aid:index'))

        symptom_list = illness.related_symptom.all()

        context_dict = {'selected_illness': illness,
                        'symptom_list': symptom_list}

        return render(request, 'dog_aid/illness_profile.html', context_dict)

class ListProfilesView(View):
    @method_decorator(login_required)
    def get(self, request):
        profiles = UserProfile.objects.all()
        return render(request, 'dog_aid/list_profiles.html', {'user_profile_list': profiles})

class ListDogProfiles(View):
    @method_decorator(login_required)
    def get(self, request):
        current_user = request.user
        dog_profiles = Dog.objects.filter(owner=current_user)
        return render(request, 'dog_aid/dog_profile_list.html', {'dog_profile_list': dog_profiles})

class ListVetProfiles(View):
    @method_decorator(login_required)
    def get(self, request):

dog_aid_project/templates/dog_aid/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load dog_aid_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Dog Aid - {% block title_block %}Welcome to Dog Aid!{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-md fixed-top bg-warning text-body p-0">
                <a class="navbar-brand p-2 text-body" href="{% url 'dog_aid:first' %}">Dog Aid</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon text-body"></span>
                </button>

                <li class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link text-body" href="{% url 'dog_aid:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link text-danger font-weight-bold" href="{% url 'dog_aid:emergency' %}">Emergency</a></li>
                        <div class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown">Profile
                            <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'dog_aid:profile' user.username %}">Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'dog_aid:register_dog' %}">Register a Dog</a></li>
                                <li><a class="dropdown-item" href="{% url 'auth_logout' %}">Log out</a></li>
                                {% else %}
                                <li><a class="dropdown-item" href="{% url 'auth_login' %}">Login</a></li>
                                <li><a class="dropdown-item" href="{% url 'dog_aid:register' %}">Register</a></li>
                                {% endif %}
                            </ul>
                        </div>
                        <div class="dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown">Illnesses
                            <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item text-danger" href="{% url 'dog_aid:emergency' %}">Emergency</a></li>
                                <li><a class="dropdown-item" href="{% url 'dog_aid:illness_all' %}">All</a></li>
                            </ul>
                        </div>
                        <div class="dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown">Vet
                            <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'dog_aid:vet_list' %}">My vets</a></li>
                                {% endif %}
                                <li><a class="dropdown-item" href="{% url 'dog_aid:vet_register' %}">Register vet</a></li>
                            </ul>
                        </div>
                        <li class="nav-item "><a class="nav-link text-body" href="{% url 'dog_aid:quiz' %}">Quiz</a></li>
                        <li class="nav-item "><a class="nav-link text-body" href="{% url 'dog_aid:training' %}">Training</a></li>
                    </ul>
                </div>
            </nav>
        </header>

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2 d-none d-md-block bg-warning sidebar">
                    <ul class="nav nav-list flex-column">
                        <div class="sidebar-sticky">
                            <div class="w-75 ml-3">
                                <li class=nav-item">Type to find an illness or symptom</li><br/>
                                <form>
                                    <li class="nav-item"><input class="search-query form-control" type="text"
                                                        name="suggestion" value="" id="suggestion" /></li>
                                </form><br/>
                                <div id="illness_suggest">
                                    {% get_illness_list illnesses %}
                                    {% get_symptom_list symptoms %}
                                </div>
                            </div>
                        </div>
                    </ul>
                </div>
            </div>
        </div>

        <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
            {% block body_block %}
            {% endblock %}

            <footer>
                <p class="float-right"><a class="text-warning" href="#">Back to top</a></p>
                <p>&copy; 2020 Dog Aid &middot; <a class="text-warning" href="#">Privacy</a> &middot; <a class="text-warning" href="#">Terms</a></p>
            </footer>
        </main>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
        <script src="{% static "js/dog_aid-ajax.js" %}"></script>

        <script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

dog_aid_project/templates/dog_aid/dog_profile.html
{% extends 'dog_aid/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Profile for {{ selected_dog.name }}
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4 bg-white border border-warning">
    <div class="container">
        <h1 class="jumbotron-heading text-success">{{ selected_dog.name }}'s Profile</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="mb-3">
                <div class="card-body card border-warning">
                    {% if dog_profile.picture %}
                    <img src="{{ MEDIA_URL }}{{ dog_profile.picture }}"
                         width="300" height="300" alt="{{ selected_dog.name }}'s profile image" />
                    {% else %}
                    <img src="{{ MEDIA_URL }}/dog_images/default.jpg" width="200" height="200"/>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="mb-2">
                <div class="card-body">
                    <h6 class="list-group" style="text-decoration: underline">
                        Dog Name: </h6>{{ dog_profile.name }}<br/><br/>
                    <h6 class="list-group" style="text-decoration: underline">
                        Date of birth: </h6>{{ dog_profile.DOB }}<br/><br/>
                    <h6 class="list-group" style="text-decoration: underline">
                        Breed: </h6>{{ dog_profile.breed }}<br/><br/>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="mb-3">
                <div class="card-body">
                    <a href="{% url 'dog_aid:vet_list' %}" class="btn btn-warning" role="button">My vets</a><br/><br/>
                    <a href="{% url 'dog_aid:register_event' %}" class="btn btn-warning" role="button">Register an event</a><br/><br/>
                    <a href="{% url 'dog_aid:vet_list' %}" class="btn btn-warning " role="button">Edit {{ dog_profile.name }}'s profile</a><br/><br/>
                    <a href="{% url 'dog_aid:profile' user.username %}" class="btn btn-warning" role="button">Back to {{ dog_profile.owner }}'s profile</a><br/><br/>
                    {% if not dog_profile.picture %}
                    <button class="btn btn-warning" role="button">Add dog picture</button><br/><br/>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div class="mb-7">
                <div class="card-body">
                    <style>table, th, td {border: 1px solid orange;}
                    th, td {padding: 5px;}
                    th {text-align: center;background-color: green;color: white;}</style>
                    <h6 style="text-decoration: underline">{{ selected_dog.name }}'s History</h6>
                    <table style="width:150%">
                        <tr>
                            <th>Date</th>
                            <th>Name</th>
                            <th>Event Type</th>
                            <th>Notes</th>
                        </tr>
                        {% if event %}
                        {% for event in event %}
                        <tr>
                            <td>{{event.date}}</td>
                            <td>{{event.name}}</td>
                            <td>{{event.event_type}}</td>
                            <td>{{event.notes}}</td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td></td>
                            <td>No events registered</td>
                            <td></td>
                            <td></td>
                        </tr>
                        {% endif %}
                    </table><br/>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dog_aid_project/templates/dog_aid/emergency_suggest.html
<!DOCTYPE html>

<ul>
    <div class="row">
        <div class="card-body">
            {% for illness in emergency_illnesses %}
                <li>
                <strong>
                      <a href="{% url 'dog_aid:illness_profile' illness %}">{{ illness }}</a>
                </strong>
                </li>
            {% endfor %}<br/>
        </div>
        <div class="card-body">
            {% for symptom in emergency_symptoms %}
                <li>
                <strong>
                    <a href="{% url 'dog_aid:symptom_profile' symptom %}">{{ symptom }}</a>
                </strong>
                </li>
            {% endfor %}
        </div>
    </div>
</div>
</ul>

dog_aid_project/templates/dog_aid/illness_profile.html
{% extends 'dog_aid/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Profile for {{ selected_illness.name }}
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4 bg-white border border-warning">
    <div class="container">
        <h1 class="jumbotron-heading text-success">{{ selected_illness.name }}</h1>
<!--        <h7>{{ selected_illness.description|linebreaks }}</h7>-->
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="mb-6">
                <div class="card-body border border-warning">
                    <div class="container">
                        <h6 style="text-decoration: underline">Description</h6>
                        {{ selected_illness.description|linebreaks }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><br/>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="mb-6">
                <div class="card-body border border-warning">
                    <div class="container">
                        <h6 style="text-decoration: underline">Symptoms</h6>
                        {% for symptom in symptom_list %}
                            <a href="{% url 'dog_aid:symptom_profile' symptom %}">
                                {{ symptom.name }}</a><br/><br/>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="mb-6">
                <div class="card-body border border-warning">
                    <div class="container">
                        <h6 style="text-decoration: underline">Treatment</h6>
                        {{ selected_illness.treatment|linebreaks }}
                            <img src="{{ MEDIA_URL }}{{ selected_illness.picture }}"width="300"
                                 height="300" alt="{{ selected_illness.name }}" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="mb-6">
                <div class="card-body border border-warning">
                    <div class="container">
                        <h6 style="text-decoration: underline">Call Vet?</h6>
                        {{ selected_illness.call_vet|linebreaks }}
                        <a href="{% url 'dog_aid:vet_list' %}" class="btn btn-warning" role="button">My vets</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><br/>
{% endblock %}

dog_aid_project/templates/dog_aid/quiz.html
{% extends 'dog_aid/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Quiz
{% endblock %}

{% block body_block %}
<h1>This is the quiz page</h1>
<div>
    here is the quiz page. <br /><br />
</div>

{% endblock %}